version: '2.4'
services:
  poll-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: polldb
      MYSQL_USER: pollman
      MYSQL_PASSWORD: bestpw
    ports:
      - "3307:3306"
    volumes:
      - ./volumes/mysql/db:/var/lib/mysql
    restart: always
    networks:
      - default

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=poll-db
      - PMA_PORT=3307
    ports:
      - "8080:80"
    depends_on:
      - poll-db
    networks:
      - default
    restart: always
